"""empty message

Revision ID: 33433c9c07bb
Revises: 
Create Date: 2020-12-02 16:30:27.300129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33433c9c07bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telecon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('monthyPrice', sa.Float(), nullable=True),
    sa.Column('setupPrice', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telecon')
    # ### end Alembic commands ###
